### ISSUE TITLE
Setup Script is not working, please check

### ISSUE THREAD

**Issue by ayushagg31** [diazabdulm/dribbble#4]
![image](https://user-images.githubusercontent.com/17214678/83543400-f3b96380-a519-11ea-93dd-8c89e17d0907.png)

**Comment by diazabdulm** [comment]
Hmm would you provide more info please? There's not much I can make out of the provided screenshot.

On a side note though, I'd admit the setup process indeed was a little confusing but, after some modifications, it should be simpler now: feel free to run `npm install` or `npm i` as you would any other project.
